name: renewables-analysis
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12

  # Core scientific stack
  - numpy>=1.26
  - pandas>=2.2
  - matplotlib>=3.9
  - seaborn>=0.13
  - scikit-learn>=1.5
  - cdsapi
  - cmocean

  # Parallel & N-D data
  - dask>=2024.8
  - xarray>=2024.7
  - netcdf4>=1.7
  - zarr>=2.18
  - numba

  # AWS / Async stack
  - aioboto3>=12.4
  - aiobotocore>=2.12,<2.16
  - aiohttp>=3.10
  - boto3>=1.24
  - botocore>=1.24
  - s3fs>=2024.6

  # Geospatial stack
  - geopandas>=1.0
  - cartopy>=0.23
  - contextily>=1.6
  - shapely>=2.0
  - adjustText>=1.3

  # Dev / Jupyter
  - pip>=24
  - jupyterlab>=4.2
  - notebook>=7.2
  - black>=24

  # Solver
  - mamba

  # Pip-only extras
  - pip:
    - jupyterlab==4.2.2 #JupyterLab computational environment
    - jupyterlab-execute-time==3.1.2 #Display cell timings in Jupyter Lab
    - notebook==7.2.1 #A web-based notebook environment for interactive computing
    - shapely==1.8.1.post1 #Manipulation and analysis of geometric object
    - black==24.10.0
